name: "Daily check and update"

on:
  schedule:
    - cron: "10 */12 * * *"
  workflow_dispatch:

jobs:
  check_and_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11

      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run main.py
        env:
          COOKIES: ${{ secrets.COOKIES }}
        run: |
          python main.py -o .github/README.md -si
      - name: Format with prettier
        run: |
          npx prettier .github/README.md --write --parser html
      - name: Commit and push if changed
        run: |
          git diff
          git config user.name "Game Stats Cron"
          git config user.email "GameStats@GameStats.com"
          git add .
          git commit -m "Game stats cron"
          git push
